[package]
name = "zfs-autosnaprs"
version = "0.1.0"
authors = ["Micha Glave <micha@glave.net>"]
edition = "2018"
description = "zfs-auto-snapshot like tool written in Rust."
license = "MIT"

[dependencies]
simplelog = "0.7.4"
structopt = "0.3.7"
log = "0.4.8"
derive_builder = "0.9.0"
chrono = "0.4.10"